name: Steam Sky
title: Steam Sky
description: >- # this means to ignore newlines until "baseurl:"
   Roguelike in a sky with steampunk theme
baseurl: "/steamsky" # the subpath of your site, e.g. /blog
url: "https://laeran.pl" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
   enabled: 
      - categories
   layout: archive
